version: "3.4"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - "./data/db:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run build
    volumes:
      - ./app/frontend
      - node-modules:/app/frontend

volumes:
  node-modules:
